### ISSUE TITLE
Going back in history after following symlink is recursive

### ISSUE THREAD

**Issue by zaucy** [zaucy/vscode-symlink-follow#1]
When traversing history back going to the symlink causes the symlink to follow again causing an infinite loop. Mainly affects people using the auto follow option.

Ideas:
1. Remove history. Not sure if there's an API for that
2. Detect going back and don't follow symlink

**Comment by vient** [comment]
FYI I created copy of this extension with this problem (kinda) fixed
https://marketplace.visualstudio.com/items?itemName=vient.symlink-follow-2
https://github.com/vient/vscode-symlink-follow/commit/9e4f4460306da49068ca346e25e13201fdc3103f#diff-04bba6a35cad1c794cbbe677678a51de13441b7a6ee8592b7b50be1f05c6f626R29-R34
