### ISSUE TITLE
Thank you! ❤️

### ISSUE THREAD

**Issue by shayanhoshyari** [zaucy/vscode-symlink-follow#10]
This is not really an issue. I just wanted to say thank you. I have been trying to get a working developer workflow with Bazel and vscode for python; and this extension combined with [PYDEVD_RESOLVE_SYMLINKS](https://github.com/microsoft/debugpy/issues/743) has made it possible!

**Comment by zaucy** [comment]
Haha appreciate it. I made it cause I was using bazel with vscode as well. Although I'm not using vscode anymore feel free to contribute like a few others have if there's any issues 🤝
